# Supervision

Supervision plays a crucial role in your doctoral training, so the decision of choosing a supervisor should be made with care and attention. Consider your substantive research interests, funding, timelines, how much time and responsiveness you may need from a supervisor, as well as a potential supervisor's existing supervision load when making your decision. Don't be afraid to ask lots of questions about a supervisor's style of working or research group policies before committing to work with someone.   

## Getting Started
By default, all doctoral students, even those that have previously discussed supervision with a faculty member, are initially advised by the designated PhD Program Advisor. The advisor's role is to provide early guidance on your academic program and career planning, to mentor you, and to serve as your advocate when necessary. Generally speaking, once a supervisor has been approved, the supervisor takes on the primary mentorship role.

Of course, this does not exclude the possibility of a student-supervisor match at admission, nor the possibility of the academic Program Advisor becoming a student's supervisor.

## Thesis Supervisor
Doctoral students are expected to identify a supervisor by no later than 15 February of their first year of study, but identifying a supervisor earlier is encouraged, as solid supervision is important for planning and making progress. 

If you currently don't have a supervisor, take the time to contact professors within the various areas of faculty research that interest you. Faculty research interests are broadly categorized on the departmental [website](https://www.mcgill.ca/epi-biostat-occh/research). It is also worthwhile networking and discussing potential supervisors with your peers and more senior doctoral students. If you wish to be supervised by an [Associate Member](https://www.mcgill.ca/epi-biostat-occh/people/field_mprofile_group/Associate%20Members) of the department it may be necessary to have a Full Member of the faculty as a co-supervisor. Contact the Student Services Office or the Program Director/Advisor for assistance.

Although uncommon, note that it is certainly possible to change thesis supervisors at any point during your training. Generally, if you plan to change supervisors, it is advantageous to do so earlier rather than later in your training. Changing supervisors has consequences for funding and possibly your thesis topic and timeline, and should be carefully considered. Before you make a decision to change, talk to the PhD program administrators.

## Requirements

Your thesis supervisor must be a McGill faculty member with an appointment in the Department of Epidemiology, Biostatistics and Occupational Health. In the course of formalizing your decision on a supervisor, note that both students and supervisors are required to sign a Letter Of Understanding. This document is designed to promote dialogue between the supervisor(s) and the graduate student to define their expectations and to increase awareness of the rights and responsibilities governing the training program and the student-supervisor relationship. The aim is to avoid problems and to achieve a positive and mutually beneficial experience. It is due at the same time as the Thesis Supervisor Nomination form, May 15 at the end of the first year. The Supervisor Nomination Form and the Letter of Understanding are available [here](https://www.mcgill.ca/epi-biostat-occh/files/epi-biostat-occh/eboh_supervisor_nomination_form-lou_201909.docx).

## Suggestions

Maintaining a mutually respectful and supportive relationship with your thesis supervisor will help make your journey through the program easier. To ensure timely progress through the degree program, we recommend discussing the following issues with your supervisor at the earliest opportunity after admission. Any unresolved issues should be reviewed periodically and agreement achieved as soon as possible. It might be helpful to attach to this checklist detailed minutes of discussions held and decisions made, as appropriate.  

**Issues to Discuss:**  

- Course plan: courses; credits by semester
- Thesis timeline: dates for protocol; completion
- Thesis format: classic or manuscript based
- Authorship: number of expected papers; content, journals; first, senior, co-authors, corresponding author; number of presentations, content, conference locations, costs
- Thesis project: possible topics; primary or secondary data collection; holding rights & responsibilities
- Members of supervisory committee: proposed; confirmed
- Committee meetings: number and timing; by semester
- Funding: personal, project
- Ethics approval: timing
- Office hours: hours, open door
- Absences: sabbatical; holidays; conferences


## Thesis supervisory committee
You are required to have a Thesis Supervisory Committee. The membership and size are determined by you and your supervisor, with the approval of the PhD Program Director or Advisor. For the PhD a minimum committee of two (your supervisor and one other member) is required, but may (and likely should) be larger, depending on how inter-disciplinary the topic is, and what other expertise is needed to support your thesis. Committee members must hold a faculty or scientist appointment at a university or research institution, though there is flexibility to include members at non-research institutions if needed. The committee should be struck at an early stage of thesis research and certainly no later than the end of the semester in which the topic has been defined.

Meetings with the entire thesis supervisory committee should be held as frequently as is necessary to ensure efficient progress of the thesis research, but at a *minimum* once per semester.

## Expectations

### Expectations for the supervisor
A Supervisor will:  

- help to define topic of dissertation;
- help to assemble Supervisory Committee;
- jointly with you, notify department in writing of topic and committee members;
- help to define exact nature and scope of dissertation;
- meet, or otherwise communicate, with you at least once a month;
- provide timely feedback;
- monitor deadlines;
- be aware of, and coordinate (and resolve any conflicts in) any advice received by you when you meeting separately with other members of Supervisory Committee or with other consultants
- hold once-a-semester meeting of full Supervisory Committee;
- when thesis is nearing completion, submit names of possible examiners to Department;
- ensure that corrections/suggestions by examiners are carried out.

### Expectations for Thesis Committee Members
Thesis Committee Members will:

- be a consultant to you and your supervisor;
- evaluate (with other members of thesis committee) and when satisfied, formally approve your research protocol;
- attend once-a-semester meeting of your full thesis committee and take active part in assessing progress and setting goals for you.

### Expectations for you
The department expects that you will:

- follow the timelines set out for the program, including submitting the required progress reports in accordance with established deadlines;
- establish a thesis committee, and convene meetings of this committee on a regular basis, ensuring there is at least one full committee meeting per semester;
- be a full-time research student, and keep research moving forward in accordance with the timetable for completion of activities noted in the annual work plan you are to submit;
- follow established norms for research integrity.

## Conflicts
Completing a PhD is a long and occasionally frustrating process for everyone involved, and conflicts between you and your supervisor (or thesis committee) may arise. In a situation of conflict with you thesis supervisor, you should follow these steps one at a time and *in the following order*:

1. speak to your supervisor
2. speak to your degree Program Advisor
3. speak to your Graduate Studies Director
4. speak to your Department Chair
5. speak to the Ombudsperson
6. speak to the Associate Dean (Graduate Studies)

See McGill's [page](www.mcgill.ca/students/srr/disputes) on resolving disputes in the Student Rights and Responsibilities section for further information.
