# Comprehensive Exam

Doctoral students will normally take the Comprehensive Exam (EPIB 701) immediately after completing the 703-704-705 course sequence. The Comprehensive Exam is held once a year in June.   

## Purpose 

The objective of the PhD comprehensive examination is to assess a student's ability to synthesize and apply knowledge of epidemiological and biostatistical principles. As is true for many doctoral level training programs, the overall rationale for a comprehensive exam is to ensure that students have the sufficient conceptual and methodological qualifications to pursue independent epidemiologic research at the highest professional level.

## Content and Structure

The format of the exam is a computer-based typed response "in class" examination designed for a test-time of 4 hours total divided into two 120 minute blocks taking place over a single day, with a break for lunch. 

During the first session students will be asked a series of questions on a selected published article (the article is made available by e-mail to students 24 hours before the in-class exam). Questions in this session test basic and advanced knowledge of epidemiologic concepts and principles, as well as of applied biostatistics.

The second session will be based on questions related to concepts of study design and interpretation, including statistical analysis. This will require students to integrate and apply their knowledge of several aspects of epidemiological and biostatistical principles.

## Evaluation

Results of the comprehensive exam will be transmitted to students within 3 weeks of the date of the exam. The exam is graded "Pass" or "Fail". Students with a "Fail" must repeat the exam in 6 months in early December. 

Students are required to pass *both* the first and second portions of the examination in order to pass the comprehensive examination. A passing grade on each portion of the examination is 65%. There is no provisional pass.

## Resources

Students are strongly encouraged to consult past exams (and more senior doctoral students) to understand better the types of questions that are likely to appear on the exam, and taking a full 'practice exam' is encouraged. Electronic copies of past exams are made available to students. 

*Note: Additional details for the exam are provided to students when they formally register for EPIB 701 by the chair of the Comprehensive Exam Committee.*
