# PhD Thesis

Thesis research is normally actively undertaken following successfully passing the comprehensive exam and defending the thesis protocol. It is expected that students will complete their degree within 48 to 60 months of entry into the PhD degree program.

A thesis for the Doctoral degree must constitute original scholarship and must be a distinct contribution to knowledge. It must show familiarity with previous work in the field and must demonstrate your ability to plan and carry out research, organize results, and defend the approach and conclusions in a scholarly manner. The research presented must meet current standards of the discipline and clearly demonstrate how the research advances knowledge in the field. Finally, the thesis must be written in compliance with norms for academic and scholarly expression and for publication in the public domain (see section: withholding a thesis from circulation temporarily). The nature of academic research requires adherence to McGill’s policies on research ethics and intellectual property, as described below.

## Nomination of Thesis Examiners
At least 2 months prior to submitting the initial thesis, students, in collaboration with their supervisor(s) and committee, must submit a Nomination of Examiners form that assists the Department in forming the Oral Defence Committee. The details, procedures, and specifications for the composition of the Committee are given below, and a fillable worksheet is available [online](https://www.mcgill.ca/epi-biostat-occh/files/epi-biostat-occh/eboh_phd_nom_exam_worksheet_201911.docx). Please do not complete the official form posted on the GPS website until your selection of names has been reviewed, approved, and an external examiner has been secured by the department.
 

### Oral Defense Committee
The oral defense committee consists of five voting members: Academic Unit representative (Chair or delegate), Supervisor (or co-supervisor, as appropriate), Internal Examiner, Internal Member, and External Member. The committee is designed to ensure a majority of members have not been closely involved with the thesis. "Closely involved" means serving on the student's supervisory committee or having meaningful input into the body of work contained in the thesis.

1. INTERNAL EXAMINER – submit two names
Usually chosen from members of the Department with expertise in the subject area of the thesis.  The supervisor must contact both proposed internal examiners and secure from them a commitment (by email) that they are willing to serve in this capacity. The internal examiner must not be in conflict of interest according to McGill’s policy (see University conflict of interest regulations).  

2. EXTERNAL EXAMINER – submit up to four, but at least two, names in a ranked order
The external examiner must hold a PhD degree, or equivalent, and should be from outside McGill. The proposed external examiners should have demonstrated epidemiologic and/or biostatistical expertise, as well as expertise in the substantive area of the thesis.  Please clearly indicate their qualifications and your main reasons for choosing them.  The Program Committee designate will validate the appropriateness of the proposed choices. In order to minimize any real or perceived conflicts of interest, the Department will contact the external examiner once approved to secure his/her commitment to evaluate the thesis.  The student or supervisor should NOT contact any of the proposed external examiners. 

External examiners must be perceived to be able to examine the student and the thesis at arm's length, free of conflict of interest from any source. The test of whether or not a conflict of interest might exist is whether a reasonable outside person could consider that a situation could give rise to an apprehension of bias. The candidate's unit must take reasonable steps to avoid recommending an examiner whose relationship with the candidate, the supervisor, or their research could be seen as jeopardizing an impartial judgment on the thesis. Any individual asked to examine a thesis must declare possible sources of conflict. The following checklist, while not exhaustive, itemizes situations that could represent conflict of interest, and thus need to be declared and generally avoided. It is the responsibility of the unit (student's supervisor, chair or designate) to complete this checklist in consultation with the nominated examiner and provide it to the Thesis Office along with the Nomination of Examiners form. An answer of YES to any question below would normally exclude this individual as an examiner. Address any queries to the Thesis Office.  

- Have you co-authored or otherwise carried out research in collaboration with the student or the supervisor (within the last five years)?
- Do you knowingly have a financial interest in an entity that could benefit from the thesis research? 
- Have you previously read the thesis, or parts of it, or evaluated the student's thesis research (e.g., as an advisor, as a supervisory committee member, evaluator for progress tracking)? 
- Have you previously examined or been examined by the student's supervisor (within the last five years), e.g., the former student or former supervisor of the student's supervisor? 
- Do you have a former or pending affiliation with the student's academic unit* (within the last five years); e.g., graduated from the same academic program or been offered an academic appointment in the unit?
- Have you held an academic appointment at McGill within the last five years? 
- Have you engaged in (or intend to engage in) discussions/negotiations with student or supervisor relating to future employment or supervision? 
- Do you have a personal or financial relationship to the student or the supervisor? 
- Relationships that might appear to have a conflict of interest include:
  - A past or present spouse or partner
  - A close family member
  - A past or present business partner
- Have you engaged in other activities that could be interpreted as conflict of interest? (please specify)  

3. INTERNAL MEMBER – submit two names
The internal member is a McGill faculty, or affiliated, member who may be associated with the student’s unit. You do not need to contact these individuals.  

4. EXTERNAL MEMBER – submit two names
The external member must not be from the unit and may be from outside McGill. The external member is distinct from the external examiner and does not submit a written report. You do not need to contact these individuals.


## Human Subjects Review
In accordance with university guidelines (Policy on the Ethical Conduct of Research Involving Human Subjects), all research involving human subjects requires ethics approval.  

Research involving human participants, animal subjects, micro-organisms, living cells, other biohazards, and/or radioactive materials must have had the appropriate compliance certification. Copies of any certificates of compliance must be retained by the supervisor and student in accordance with McGill’s policies on research ethics. Supervisors indicate on the Nomination of Examiners and Thesis Submission Form that the thesis research has complied with all ethical standards. See the Ethics and Compliance webpage for further information about certification and training requirements.

Even if your supervisor has already obtained IRB approval for the larger research study of which your thesis work forms just a part, the departments insists (partly since you defend the thesis as *your* work, partly for training purposes) that you obtain IRB approval of the specific work you are doing, and include this specific approval (in addition to those for the broader project) in your own thesis.

The definition of "research involving human subjects" is broad. See [Student Guide To Ethics Review](https://www.mcgill.ca/research/researchers/compliance/human) For Research Involving Human Subjects. This document also describes research involving human subjects which does not require ethics review. If still in doubt, additional advice can be obtained from the Program Advisor or Director.

Applications for ethics approval should be directed to the [Faculty of Medicine Research Ethics Board](https://www.mcgill.ca/medresearch/ethics) (commonly referred to as the Institutional Review Board or IRB) or to one of the following Affiliated Hospital Research Ethics Boards: the [McGill University Health Centre](https://muhc.ca/cae/page/research-ethics), the [Douglas Hospital](http://www.douglas.qc.ca/page/ethics), the [SMBD Jewish General Hospital](http://www.jgh.ca/en/ResearchEthicsCommittee) or the [St. Mary's Hospital Centre](http://www.stmarysresearch.ca/en/research_review/research-review).

In addition, you must complete the on-line interactive [tutorial](http://www.pre.ethics.gc.ca/eng/education/tutorial-didacticiel/) on research ethics released by the Interagency Advisory Panel on Research Ethics (PRE), a multidisciplinary body mandated by the three granting agencies to further develop the Tri-Council Policy Statement: Ethical Conduct for Research Involving Humans (TCPS).This tutorial is a voluntary independent learning tool covering the first five chapters of the TCPS. It includes case studies, progress checks and a printable certificate of completion. The tutorial is the only one of its kind in Canada on research ethics involving humans and is offered in both French and English. It is intended for researchers, students, members of Research Ethics Boards, administrators, research participants and the general public.

## Thesis Format
"Official" guidelines for doctoral theses are [provided](https://www.mcgill.ca/gps/thesis/thesis-guidelines/preparation) by the Office of Graduate and Postdoctoral studies. There are different requirements for traditional "monograph-based" theses and "manuscript-based" theses, the latter of which most students in Epidemiology have published in recent years. 

Each year the Department organizes thesis-writing workshops that go over the details related to thesis submission, issues related to formatting, and provide links to resources for writing. The last workshop slides are available [here](data/PhD_Epi_Thesis_Writing_Workshop_9May2023_KHayden.pdf) and [here](data/thesis-workshop-PhD-2023-05-09.pdf). 

## MyThesis

Doctoral students are required to use McGill's [MyThesis](https://www.mcgill.ca/gps/thesis/thesis-guidelines/initial-submission/what-mythesis) portal to submit their thesis. myThesis is a thesis examination management system for McGill graduate students. It is part of the myProgress hub. McGill graduate students are required to use myThesis: 1) to notify their supervisors in advance of their intent to submit their thesis; 2) to nominate thesis examiners; and 3) for their initial thesis submission. Examiners are also able to use myThesis to retrieve the initial thesis, and to complete and submit their evaluation.

A schematic of the entire MyThesis timeline is provided on the GPS [website](https://www.mcgill.ca/gps/files/gps/mcgill_mythesis_overview_of_process.pdf).