# Policies

## Progress Tracking
Each year the Department requires PhD students to submit an annual tracking form. This is to be done in *collaboration* with your supervisor(s) and helps the Department to monitor your progress toward completing your degree as well as providing a shared opportunity to set goals and review progress with your supervisor(s). The departmental tracking form can be found [here](https://www.mcgill.ca/epi-biostat-occh/files/epi-biostat-occh/gps_gradstudent_progress_tracking_report_2020.pdf)

This is a mandatory policy and procedure to track the research progress of graduate students. Students should familiarize themselves with this policy by reviewing the full text available on the GPS [website](https://www.mcgill.ca/gps/students/progress-tracking).

Timeline: May 15 of each year.

With the first tracking form, students should submit proof of completion of the Tri-Council Policy Statement 2 (TCPS2) Course on Research Ethics (CORE) (see below for details).

## Research Ethics 
As of January 15, 2016, all McGill University students (undergraduate, graduate, postdoctoral), faculty and staff engaging in human subjects research must complete human research ethics training prior to submitting an application for ethics review.

This requirement can be fulfilled by completing the Tri-Council Policy Statement 2 (TCPS2) Course on Research Ethics (CORE).

To complete the online CORE tutorial go to the TCPS2 [website](http://tcps2core.ca/welcome) and create an account. Select McGill as your institution and use your McGill email address to complete the training.

If you are new to McGill and have already completed the CORE tutorial with another institution, you can change your profile information to McGill University by logging onto the tutorial and modifying your Account Details to revise your affiliation and email address. Completion can then be verified online by the McGill Research Ethics Office.

You will also be able to print a certificate of completion for your records. The tutorial is available in English and French. The contact person for the program is 

Contact:
Ilde Lepore, Ethics Officer [(email)](mailto:ilde.lepore@mcgill.ca)
Faculty of Medicine Research, Graduate Studies and IRB
514-398-8302

## Fast-Track from MSc to PhD

**The transfer policy applies ONLY to students in Epidemiology and Biostatistics programs.** A student who has been accepted into the MSc program can request transfer into the PhD program. The formal transfer into the PhD program should occur within 12 months of initial enrollment in the Master's program.

In order to transfer from the MSc to the PhD program, the MSc student must complete all required courses for the MSc program with a minimum GPA of 3.7.

**REQUIRED DOCUMENTS**

- A three to five-page outline of the proposed PhD thesis proposal including:  
  - Research question;
  - Background and brief literature review indicating the importance of the proposed research;
  - Preliminary research design, data source(s), and analysis plan;
  - A timeline for completion of the PhD program;
- Letters of support from the current MSc supervisor(s) and proposed PhD supervisor(s). In cases where this is the same person, one additional letter from a faculty member in the Department is required. The letter from the proposed PhD supervisor(s) must include a statement of financial support for the candidate and research.

The transfer application material must be submitted by **April 25** to the Student Services Office (gradadmin.eboh@mcgill.ca).

## Policy on Departmental Seminars

The Department considers attendance at its seminars an important component of training and expects all students to attend as frequently as possible.

EBOH PhD students will be expected to attend 60% of the Epidemiology Seminars each term irrespective of their program year. Attendance at seminars will be mandatory to maintain "good standing" during academic studies. This means that attendance at seminars will be required to maintain eligibility for Departmental support for prizes, financial aid, travel awards, studentship applications, etc. Attendance at Biostatistics or at other seminars on campus or in teaching hospitals (depending on one's areas of interest) will be encouraged but will not be mandatory.

Students who will be unable to attend 60% of the seminars should send a request for an exemption to the Chair's office justifying their absence (e.g., residing outside of Montreal, travel relating to their studies, family reasons).

## Teaching Assistantship

All doctoral students are required to hold a teaching assistant position *at least once* during your training. Regardless of whether or not doctoral students may be interested in an academic career, the hands-on experience of course preparation, didactic and one-on-one explanation, and student mentoring are valuable skills for any scientist. Teaching is also an excellent opportunity to revisit and master core epidemiological concepts, and the experience of explaining and mentoring other students can help to reinforce other aspects of your epidemiology training. 

## Policy on Email

University Policy Concerning E-Mail As An Official Means Of Communication With Students. E-mail is an official means of communication between McGill University and its students.
 
In order to satisfy the need for timely and efficient communication, and to provide a better service to its students, McGill University has instituted a policy that establishes e-mail as an official means of communicating with students.

Upon registration at McGill, each student is assigned an official McGill e-mail address and a McGill e-mail box. This address may be viewed and verified via Minerva, under the Personal menu.

The McGill E-mail Address points to the McGill e-mail box by default for all students. As with all official University communications, it is the student's responsibility to ensure that time-critical e-mail is accessed, read, and acted upon in a timely fashion. If a student chooses to forward University e-mail to another e-mail mailbox, it is that student's responsibility to ensure that the alternate account is viable.

This policy applies to all McGill students and employees who manage official communications with students.

For confidential and official communication requiring an original signature, communication is by (physical) mail. Therefore, please ensure that your current postal address is updated on Minerva.  Students must also inform the Student Affairs Office and complete the details in Minerva.
