# Funding

## Departmental Obligations

The Department, jointly with the PhD student's supervisor, offers an annual funding package valued at a *minimum* of \$27,215 (\$27,725 for international students) for a *maximum* of four years. This is comprised of $22,000 for living expenses, with the remainder to cover tuition (at the QC/CA/PR level) and fees (including International health & GPS supplemental health plans). In addition, the Department will use different mechanisms such as Differential Fee Waivers to cover the additional tuition for international students so that they pay tuition at the same level as Canadian students.

Note that financial support is conditional upon academic performance, as well as **student efforts to apply for all external/internal graduate fellowship funding for which they are eligible**, including CIHR, FRQS, SSHRC, NSERC, etc., as well as the McGill Faculty of Medicine & Health Sciences and Hospital Research Institute competitions.

## External Awards

Students may only submit one application per year to a Tri-Council funding agencies (CIHR, NSERC, or SSHRC).

Information sessions are held in mid-to-late September for students to obtain information about the main graduate fellowships. These sessions are convened by agency representatives and McGill professors involved on adjudication committees. See the GPS Website for specific dates and locations. The department often receives notices about various awards for students; these are sent to students via e-mail. There are many other fellowships/scholarships available. See those listed on the Graduate and Postdoctoral Studies [website](https://www.mcgill.ca/gps/funding/opportunities/phd). Also, do some searching of your own on the internet. Sometimes you may be eligible for fellowships provided by agencies in your home province or country.

### Canadian Institute of Health Research (CIHR)

Value:	\$35,000 per year  
Duration:	36 months  
Tenure: Canadian institutions only  
Application deadline: October 5th, 2023

- Through a Canadian institution: Contact your institution 
- Directly to the agencies: October 17th, 2023

To be considered eligible for support by CIHR, you must:  

- be a Canadian citizen or permanent resident of Canada;
- be registered in full-time studies in a Canadian graduate school;
- have achieved first-class average at McGill (i.e., A- or 3.70); 

Individuals with a health professional degree who seek support for doctoral research training are eligible to apply for the CIHR Doctoral Research Award. Please note that a person holding a health professional degree would receive a higher stipend only through the CIHR Fellowships program.

- Students pursuing an MD/PhD may apply for a Doctoral Research Award but should also consider the MD/PhD Studentships Program.

See CIHR's [website](https://www.nserc-crsng.gc.ca/Students-Etudiants/PG-CS/CGSD-BESCD_eng.asp) for further information.

### Fonds de la Recherche en santé du Québec (FRSQ/FRQS)  

Competition year: 2023-2024  
Deadline (application):  October 5th, 2023 at 16:00 (EST)  
Announcement of results: April 2024  
Amount: \$25 000 per year  
Duration: 4 years  


To be considered eligible for support, on the deadline date, you must:  

eligible to apply for a doctoral training scholarship, applicants must:  

- Be a Canadian citizen or permanent resident AND
- Have a health insurance card issued by the Régie de l’assurance maladie du Québec (RAMQ) valid at the competition deadline, or proof that a health insurance card has been requested from the RAMQ and that the card will be valid at the competition deadline.

If either of the above conditions is not met, the applicant must submit one of the following documents to be eligible:

- Proof of admission to a program of study eligible for this scholarship program (see section 3.1.1) at a Québec university OR
- An acceptance form from the research supervisor at a Québec university (“Supervisor’s form”).

See the FRQS [website](https://frq.gouv.qc.ca/en/program/doctoral-training-scholarships-frqs-2024-2025) for current information.

### Natural Science & Engineering Research Council (NSERC)

Value:	\$21,000 per year  
Duration:	36 months  
Tenure: Canadian institutions only  
Application deadline: October 5th, 2023

- Through a Canadian institution: Contact your institution
- Directly to the agencies: October 17th, 2023  

To be considered eligible for support, on the deadline date, you must:  

- be a Canadian citizen, or a permanent resident of Canada;
- hold, or expect to hold (at the time you take up the award), a degree in science or engineering from a university whose standing is acceptable to NSERC;
- intend to pursue in the following year full-time graduate studies and research at the Master's or Doctoral level in one of the areas of the natural sciences or engineering supported by NSERC.  

See the NSERC [website](https://www.nserc-crsng.gc.ca/OnlineServices-ServicesEnLigne/instructions/201/pgs-pdf_eng.asp) for current information.
