project:
  type: book
  output-dir: docs

book:
  title: "![](mcgill-epi-logo.png){width=600px} <br><br> PhD Handbook <br> 2024-2025 Academic Year </br>"
  output-file: "phd-handbook"
  author: "PhD Program Leadership"
  page-footer:
    right: 
      - text: "Last updated: 2024-09-03"
  # date: 
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-supervision.qmd
    - 03-coursework.qmd
    - 04-concentrations.qmd
    - 05-md-phd.qmd
    - 06-comps.qmd
    - 07-protocol.qmd
    - 08-thesis.qmd
    - 09-policies.qmd
    - 10-funding.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{scrlayer-scrpage}
        \chead{}
        \rofoot{Last updated: 2024-09-03}



