# Concentrations
There are presently 3 options for Epidemiology PhD students that wish to pursue concentrated work in substantive areas related to either Global Health, Pharmacoepidemiology, or Population Dynamics. In addition to the other milestones for the PhD degree (Comprehensive Exam, Protocol Defence, Thesis Defence), these options all require additional courses to be completed *in addition to* the required courses for all Epidemiology PhD students. 

## Global Health Option
This option will provide enhanced training in global health to graduate students registered in the PhD in Epidemiology; Global Health degree program at McGill. Students will become familiar with topics of global health relevance and incorporate this into their core coursework and thesis research. The thesis must be relevant to global health and approved by the Global Health Coordinating Committee. Contextualizing the core training students receive in epidemiology and in their respective substantive discipline within the global health research domain will enhance their academic experience. Graduates of this option will be prepared to pursue further training in global health or to undertake a variety of career opportunities in global health in Canada or internationally. The PhD thesis must be relevant to global health and approved by the Global Health Coordinating Committee.

**Required Courses (22 credits)**  

*Option-specific courses are italicized*

- *EPIB 681 Global Health: Epidemiologic Research (3 Credits)*
- *PPHS 511 Fundamentals of Global Health (3 Credits)*
- EPIB 701 PhD Comprehensive Examination
- EPIB 702 PhD Proposal
- EPIB 703 Principles of Study Design (2 Credits)
- EPIB 704 Doctoral Level Epidemiologic Methods 1 (4 Credits)
- EPIB 705 Doctoral Level Epidemiologic Methods 2 (4 Credits)
- EPIB 706 Doctoral Seminar in Epidemiology (3 Credits)
- EPIB 707 Research Design in the Health Sciences (3 Credits)

**Complementary Courses (9 credits)**  

6 credits of coursework at the 500 level or higher, with a minimum of 3 credits in Biostatistics, and 3 credits in Epidemiology. Courses must be chosen in consultation with the student's supervisor and/or the degree program's director or adviser.

3 credits of coursework at the 500 level or higher from this list, or any other course *approved by the Global Health Option Committee* that have not been taken to satisfy other program requirements.

- GEOG 503 Advanced Topics in Health Geog 3 Credits
- NUTR 501 Nutrition in Dev Countries 3 Credits
- PPHS 525 HlthCare Systems in Comp Persp 3 Credits
- PPHS 527 Econ for Hlth Serv Res&Policy 3 Credits
- PPHS 529 Global Env Hlth&Burden/Disease 3 Credits
- SOCI 513 Soc Aspects HIV/AIDS in Africa 3 Credits
- SOCI 519 Gender and Globalization 3 Credits
- SOCI 545 Sociology of Population 3 Credits

Please contact the Global Health Option Advisor [Madhu Pai](mailto:madhukar.pai@mcgill.ca) for any questions regarding this option.


## Pharmacoepidemiology Option
This program provides in-depth training for graduate students on pharmacoepidemiologic methods and the application of these methods to study the population effects (benefits and harms) of pharmaceutical products. Students will acquire the skills to become independent investigators and conduct original research in pharmacoepidemiology. Career opportunities for graduates are multiple and include work in industry, government, or academia. Students will be required to participate in the Pharmacoepidemiology Journal Club. Research topics must be related to pharmacoepidemiology and approved by the program coordinating committee.

**Required Courses (25 credits)**    

*Option-specific courses are italicized*

- *EPIB 639 Pharmacoepidemiologic Methods (4 Credits)*
- *EPIB 654 Pharmacoepidemiology 4 (2 Credits)*
- *EPIB 661 Pharmacoepidemiology 3 (2 Credits)*
- *EPIB 662 Pharma Basis of Pharmacoepidem (1 Credit)*
- EPIB 701 PhD Comprehensive Examination
- EPIB 702 PhD Proposal
- EPIB 703 Principles of Study Design (2 Credits)
- EPIB 704 Doctoral Level Epidemiologic Methods 1 (4 Credits)
- EPIB 705 Doctoral Level Epidemiologic Methods 2 (4 Credits)
- EPIB 706 Doctoral Seminar in Epidemiology (3 Credits)
- EPIB 707 Research Design in the Health Sciences (3 Credits)

**Complementary Courses (3 credits)**

3 credits of coursework in Biostatistics at the 500 level or higher. Courses must be chosen in consultation with the student’s supervisor and/or the degree program’s director or adviser.

These courses can be chosen from the Department's current offer of more than 40 courses in Epidemiology, Biostatistics and Occupational Health as well as from other McGill Departments. 

Please contact the Pharmacoepidemiology Option Advisor [Robert Platt](mailto:robert.platt@mcgill.ca) for any questions regarding this option.

## Population Dynamics Option
The Population Dynamics Option (PDO) is a cross-disciplinary, cross-faculty graduate program offered by the Centre on Population Dynamics (CPD) as an option within existing master's and doctoral degree programs in the Departments of Sociology, Economics, and Epidemiology, Biostatistics and Occupational Health (EBOH) at McGill. Students who have been admitted through their home department or faculty may apply for admission to the option. The option is coordinated by the CPD, in partnership with participating academic units.

Thus, in addition to the rigorous training provided in the Department of EBOH, graduate students who choose this option become Centre on Population Dynamics (CPD) student trainees. This affiliation notably offers opportunities for interdisciplinary research and supervision. The option also provides a forum whereby graduate students bring their disciplinary perspectives together and enrich each other's learning through structured courses, a weekly seminar series, and informal discussions and networking.

With interdisciplinary research being increasingly important to understanding complex social and biological processes, CPD student trainees benefit from both a strong disciplinary foundation from their departmental affiliations, as well as from the sharing of knowledge across disciplinary boundaries through CPD activities.

**Required Courses (22 credits)**  

*Option-specific courses are italicized*

- EPIB 701 PhD Comprehensive Examination
- EPIB 702 PhD Proposal
- EPIB 703 Principles of Study Design (2 Credits)
- EPIB 704 Doctoral Level Epidemiologic Methods 1 (4 Credits)
- EPIB 705 Doctoral Level Epidemiologic Methods 2 (4 Credits)
- EPIB 706 Doctoral Seminar in Epidemiology (3 Credits)
- EPIB 707 Research Design in the Health Sciences (3 Credits)
- *SOCI 545 Sociology of Population (3 Credits)*
- *SOCI 626 Demographic Methods (3 Credits)*

**Complementary Courses (9 credits)**

9 credits of coursework, at the 500 level or higher, with a minimum of 3 credits in Biostatistics, 3 credits in Epidemiology, and 3 credits from courses approved for the Population Dynamics Option from the list below:

- ECON 622 Public Finance (3 Credits)
- ECON 634 Economic Development 3 (3 Credits)
- ECON 641 Labour Economics (3 Credits)
- ECON 734 Economic Development 4 (3 Credits)
- ECON 741 Advanced Labour Economics (3 Credits)
- ECON 742 Empirical Microeconomics (3 Credits)
- ECON 744 Health Economics (3 Credits)
- EPIB 648 Methods in Social Epidemiology (3 Credits)
- EPIB 681 Global Health: Epidemiological Research (3 Credits)
- PPHS 525 Health Care Systems in Comparative Perspective (3 Credits)
- PPHS 528 Economic Eval of Hlth Programs (3 Credits)
- PPHS 529 Global Env Hlth&Burden/Disease (3 Credits)
- PPHS 615 Intro:Infectious Disease Epid (3 Credits)
- SOCI 502 Sociology of Fertility (3 Credits)
- SOCI 512 Ethnicity & Public Policy (3 Credits)
- SOCI 513 Soc Aspects HIV/AIDS in Africa (3 Credits)
- SOCI 520 Migration and Immigrant Groups (3 Credits)
- SOCI 535 Sociology of the Family (3 Credits)
- SOCI 588 Biosociology/Biodemography (3 Credits)

Courses must be chosen in consultation with the student's supervisor and/or the degree program's director or adviser.

Please contact the Population Dynamics Option Advisor [Amelie Quesnel-Valee](mailto:amelie.quesnelvallee@mcgill.ca) for any questions regarding this option.