# Funding

## Departmental Obligations

The Department, jointly with the PhD student's supervisor, offers an annual funding package valued at a *minimum* of \$26,500 for a *maximum* of four years. For international PhD students an additional \$1000 is included to cover the cost of compulsory participation in the McGill International Health Insurance plan. In addition, the Department will use different mechanisms such as Differential Fee Waivers to cover the additional tuition for international students so that they pay tuition at the same level as Canadian students.

Note that financial support is conditional upon academic performance, as well as **student efforts to apply for all external/internal graduate fellowship funding for which they are eligible**, including CIHR, FRQS, SSHRC, NSERC, etc., as well as the McGill Faculty of Medicine & Health Sciences and Hospital Research Institute competitions.

## External Awards

Students may only submit one application per year to a Tri-Council funding agencies (CIHR, NSERC, or SSHRC).

Information sessions are held in mid-to-late September for students to obtain information about the main graduate fellowships. These sessions are convened by agency representatives and McGill professors involved on adjudication committees. See the GPS Website for specific dates and locations. The department often receives notices about various awards for students; these are sent to students via e-mail. There are many other fellowships/scholarships available. See those listed on the Graduate and Postdoctoral Studies [website](www.mcgill.ca/gps/students/fellowships). Also, do some searching of your own on the internet. Sometimes you may be eligible for fellowships provided by agencies in your home province or country.

### Canadian Institute of Health Research (CIHR)

Value:	\$35,000 per year  
Duration:	36 months  
Tenure: Canadian institutions only  
Application deadline: 

- Through a Canadian institution: Contact your institution 
- Directly to the agencies: October 17, 2022

To be considered eligible for support by CIHR, you must:  

- be a Canadian citizen or permanent resident of Canada;
- be registered in full-time studies in a Canadian graduate school;
- have achieved first-class average at McGill (i.e., A- or 3.70); 

Individuals with a health professional degree who seek support for doctoral research training are eligible to apply for the CIHR Doctoral Research Award. Please note that a person holding a health professional degree would receive a higher stipend only through the CIHR Fellowships program.

- Students pursuing an MD/PhD may apply for a Doctoral Research Award but should also consider the MD/PhD Studentships Program.

See CIHR's [website](www.cihr-irsc.gc.ca) for further information.

### Fonds de la Recherche en santé du Québec (FRSQ/FRQS)  

Competition year: 2022-2023  
Deadline (application):  October 5th, 2021 at 16:00 (EST)  
Announcement of results: April 2022  
Amount: \$21 000 per year  
Duration: 4 years  


To be considered eligible for support, on the deadline date, you must:  

- be a Canadian citizen or a permanent resident of Canada OR
  - enrolled in a Québec university for at least two (2) full-time semesters (or the equivalent) in the three (3) semesters prior to the competition deadline. The competition semester is excluded from the calculation of the 2 full-time sessions among the 3 sessions preceding the closing date of the competition OR
  - have a health insurance card from the Régie d’assurance maladie du Québec (RAMQ) that is valid at the competition deadline or proof that an application for a health insurance card was filed with the RAMQ and that the card will be valid at the competition deadline. 

See the FRQS [website](https://frq.gouv.qc.ca/en/program/formation-de-doctorat-2022-2023) for current information.

### Natural Science & Engineering Research Council (NSERC)

Value:	\$35,000 per year  
Duration:	36 months  
Tenure: Canadian institutions only  
Application deadline: 

- Through a Canadian institution: Contact your institution
- Directly to the agencies: October 17, 2022  

To be considered eligible for support, on the deadline date, you must:  

- be a Canadian citizen, or a permanent resident of Canada;
- hold, or expect to hold (at the time you take up the award), a degree in science or engineering from a university whose standing is acceptable to NSERC;
- intend to pursue in the following year full-time graduate studies and research at the Master's or Doctoral level in one of the areas of the natural sciences or engineering supported by NSERC.  

See the NSERC [website](https://www.nserc-crsng.gc.ca/OnlineServices-ServicesEnLigne/instructions/201/pgs-pdf_eng.asp) for current information.
